/**
 * Agent Orchestrator
 * Coordinates multiple AI agents to review a PR
 * 
 * Current Agents:
 * 1. Intent Agent - Understands what changed and why
 * 2. Code Quality Agent - Reviews for bugs and quality issues
 * 
 * Future Agents (ready to plug in):
 * 3. Architecture Agent - Validates against repo rules
 * 4. Risk Agent - Assesses blast radius
 * 5. Learning Agent - Provides feedback loop
 * 6. Summary Agent - Creates human-readable summary
 */

import { IntentAgent } from "./intent-agent.js";
import { CodeQualityAgent } from "./code-quality-agent.js";

export class AgentOrchestrator {
  constructor() {
    this.agents = [
      new IntentAgent(),
      new CodeQualityAgent(),
      // Future agents will be added here:
      // new ArchitectureAgent(),
      // new RiskAgent(),
      // new LearningAgent(),
    ];
  }

  /**
   * Run all agents on a PR
   * @param {Object} context - { pr, files, octokit, owner, repo, pull_number }
   * @param {string} apiKey - OpenAI API key
   * @returns {Object} Combined results from all agents
   */
  async runAllAgents(context, apiKey) {
    console.log(`\n🤖 Starting Multi-Agent PR Review`);
    console.log(`   PR: #${context.pull_number} - "${context.pr.title}"`);
    console.log(`   Files changed: ${context.files.length}`);
    console.log(`   Agents: ${this.agents.length}\n`);

    const results = {
      agentResults: {},
      combinedMarkdown: "",
      metadata: {
        pr: context.pr,
        filesReviewed: context.files.length,
        timestamp: new Date().toISOString(),
      },
    };

    // Build combined context for agents
    const agentContext = {
      pr: context.pr,
      files: context.files,
      combinedDiff: this.buildCombinedDiff(context.files),
      octokit: context.octokit,
      owner: context.owner,
      repo: context.repo,
      pull_number: context.pull_number,
    };

    // Run agents sequentially (each can use previous results)
    for (const agent of this.agents) {
      console.log(`\n${"=".repeat(60)}`);
      console.log(`Running: ${agent.name}`);
      console.log(`${"=".repeat(60)}`);

      try {
        const startTime = Date.now();
        
        // Pass previous results as context
        const enrichedContext = {
          ...agentContext,
          intentAnalysis: results.agentResults.intentAgent,
          codeQualityAnalysis: results.agentResults.codeQualityAgent,
        };

        const agentResult = await agent.analyze(enrichedContext, apiKey);
        const duration = Date.now() - startTime;

        // Store results
        const agentKey = this.getAgentKey(agent.name);
        results.agentResults[agentKey] = agentResult;

        console.log(`✅ ${agent.name} completed in ${duration}ms\n`);
      } catch (error) {
        console.error(`❌ ${agent.name} failed:`, error.message);
        results.agentResults[this.getAgentKey(agent.name)] = {
          error: error.message,
          status: "failed",
        };
      }
    }

    // Generate combined markdown summary
    results.combinedMarkdown = this.buildCombinedMarkdown(results.agentResults);

    // Extract key metrics for GitHub status
    results.summary = this.buildSummary(results.agentResults);

    console.log(`\n${"=".repeat(60)}`);
    console.log(`Multi-Agent Review Complete`);
    console.log(`${"=".repeat(60)}\n`);

    return results;
  }

  /**
   * Build combined diff from all files
   */
  buildCombinedDiff(files) {
    return files
      .filter(f => f.patch)
      .map(f => `diff --git a/${f.filename} b/${f.filename}\n${f.patch}`)
      .join("\n\n");
  }

  /**
   * Convert agent name to key
   */
  getAgentKey(agentName) {
    return agentName
      .toLowerCase()
      .replace(/\s+/g, "")
      .replace("agent", "Agent");
  }

  /**
   * Build combined markdown from all agent results
   */
  buildCombinedMarkdown(agentResults) {
    let markdown = `# 🤖 Multi-Agent PR Review\n\n`;
    markdown += `*Generated by NirikshanAI Multi-Agent System*\n\n`;
    markdown += `---\n\n`;

    // Intent Agent section
    if (agentResults.intentAgent && !agentResults.intentAgent.error) {
      const intentAgent = new IntentAgent();
      markdown += intentAgent.format(agentResults.intentAgent);
      markdown += `\n\n---\n\n`;
    }

    // Code Quality Agent section
    if (agentResults.codeQualityAgent && !agentResults.codeQualityAgent.error) {
      const qualityAgent = new CodeQualityAgent();
      markdown += qualityAgent.format(agentResults.codeQualityAgent);
      markdown += `\n\n---\n\n`;
    }

    // Future agents will add their sections here

    markdown += `\n\n*Powered by **NirikshanAI** Multi-Agent System*`;

    return markdown;
  }

  /**
   * Build summary for GitHub status and labels
   */
  buildSummary(agentResults) {
    const summary = {
      intentAnalysis: agentResults.intentAgent,
      issuesFound: 0,
      hasHighSeverity: false,
      riskLevel: "low",
      changeType: "unknown",
    };

    // Extract from Intent Agent
    if (agentResults.intentAgent && !agentResults.intentAgent.error) {
      summary.riskLevel = agentResults.intentAgent.riskLevel || "low";
      summary.changeType = agentResults.intentAgent.changeType || "unknown";
    }

    // Extract from Code Quality Agent
    if (agentResults.codeQualityAgent && !agentResults.codeQualityAgent.error) {
      summary.issuesFound = agentResults.codeQualityAgent.totalIssues || 0;
      summary.hasHighSeverity = agentResults.codeQualityAgent.hasHighSeverity || false;
    }

    return summary;
  }

  /**
   * Create inline comments from agent results
   */
  buildInlineComments(agentResults) {
    const comments = [];

    // Code Quality Agent comments
    if (agentResults.codeQualityAgent?.fileReviews) {
      for (const fileReview of agentResults.codeQualityAgent.fileReviews) {
        for (const issue of fileReview.issues) {
          const severityEmoji = {
            blocker: "🚨",
            high: "🔴",
            medium: "🟡",
            low: "🔵",
          }[issue.severity] || "⚪";

          comments.push({
            path: fileReview.filename,
            line: issue.line,
            body: `${severityEmoji} **${issue.severity.toUpperCase()}**

${issue.description}

**💡 Suggestion:**
${issue.suggestion}

---
*Identified by: Code Quality Agent*`,
          });
        }
      }
    }

    return comments;
  }
}

